name: Scrape latest data

on:
  schedule:
    - cron: '14 10 * * *'
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Scrape official site
      run: bundle exec ruby bin/scraper/official.rb | tee data/official.csv
    - name: Get current wikidata list
      run: bundle exec ruby bin/scraper/wikidata.rb | tee data/wikidata.csv
    - name: Generate diff
      run: bundle exec ruby bin/diff.rb | tee data/diff.csv
    - name: Commit and push if it changed
      run: |-
        timestamp=$(date -u)
        echo $timestamp > data/.lastrun
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data
        git commit -m "Update data: ${timestamp}" || exit 0
        git push
